@startuml
 skinparam object {
   BackgroundColor LightYellow
   BorderColor DarkGreen
 }

object "p1: Passenger" as p1  {
  PassengerID = 1000
  Name = "First User"
  IITGNEmail = "first.user@iitgn.ac.in"
  MobileNumber = "9988776655"
  DateOfBirth = 1999-12-31
}

object "b1: Bus" as b1  {
  BusID = 101
  BusRegistrationNumber = "GJ-12-MH-1234"
  Capacity = 29
}

object "d1: Driver" as d1  {
  DriverID = 10
  DriverName = "First Driver"
  DriverMobileNumber = "9876543210"
}

object "r1: Route" as r1 {
  RouteID = 3
  StartLocation = "IIT Gandhinagar Campus"
  EndLocation = "Sargasan"
  IntermediateLocations = "Raksha Shakti Circle, Kudasan"
}

object "s1: Schedule" as s1  {
  JourneyID = 1055
  BusID = 101
  DriverID = 10
  RouteID = 3
  StartTime = 19:30:00
  EndTime = 20:00:00
  DepartureDay = 2025-04-01
}

object "bk1: Bookings" as bk1  {
  BookingID = 2032
  JourneyID = 1055
  UserID = 1000
  Seat = 22
}

object "bd1: Boarding" as bd1  {
  BookingID = 2032
  JourneyID = 1055
  JourneyDate = 2025-04-02
  Boarded = true
}

object "ll1: LiveLocation" as ll1  {
  LocationID = 3015
  BusID = 101
  Latitude = 23.2050
  Longitude = 72.6400
  LastUpdatedTime = 19:41:23
}

object "pen1: Penalty" as pen1  {
  PenaltyID = 4001
  UserID = 1000
  NumberOfMisses = 1
  PenaltyAmount = 50
  PenaltyDate = 2025-03-25
}

object "a1: Authorities" as a1 {
  AuthorityID = 1
  Name = "Admin Authority"
  Email = "admin@iitgn.ac.in"
  Password = "hashed_password"
}

object "f1: Feedback" as f1 {
  FeedbackID = 5001
  UserID = 1000
  BusID = 101
  FeedbackText = "Great service!"
  Rating = 5
  FeedbackDate = 2025-03-30
}

object "t1: Tickets" as t1 {
  TicketID = "TICKET12345"
  BookingID = 2032
  Departure_Date = 2025-04-01
  StartTime = 19:30:00
  EndTime = 20:00:00
  SeatNumber = 22
  CreatedAt = 2025-03-31 10:00:00
}


' --- Links between Objects ---

p1 -- bk1 : Books Ticket
b1 -- s1 : Serves for Schedule
f1 -- b1 : Feedback for Bus
d1 -- s1 : Drives for Schedule
r1 -- s1 : Follows Route
s1 -- bk1 : Books for Journey
bk1 -- bd1 : Verifies Boarding against Booking
b1 -- ll1 : Shares Live Location
p1 -- pen1 : Penalizes User
p1 -- f1 : Provides Feedback
bk1 -- t1 : Generates Ticket
bd1 -- s1 : Verification against a Schedul
a1 -- f1 : Manages Feedback
a1 -- s1 : Manages Schedule
a1 -- b1 : Manages Bus
a1 -- d1 : Manages Driver
a1 -- r1 : Manages Route
a1 -- s1 : Manages Schedule
a1 -- bk1 : Monitors Bookings
a1 -- pen1 : Monitors Penalties
@enduml
